# Write your query or mutation here
query Search {
  search(filter: {
    include: {
      shapeIdentifiers: ["album"]
    }
  }, language:"en") {
    edges {
      node {
        path
      }
    }
  }
}